export default [
    {
        paletteName: 'Dark UI',
        id: 'dark-ui',
        colors: [
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
            { name: 'red', color: '#F44336' },
        ],
    },
];
